spring:
  flyway:
    enabled: true
    locations:
      - classpath:schema/update
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: validate
    show-sql: false
cj.software.movie:
  relational-world:
    num-actors: 100
    num-movies: 1000
    min-roles-per-movie: 5
    max-roles-per-movie: 15
    actor-family-name:
      min: 5
      max: 20
    actor-given-name:
      min: 8
      max: 30
    actor-generation-block-size: 50
    min-actor-name-length: 5
    max-actor-name-length: 20
    min-movie-name-length: 12
    max-movie-name-length: 30
    movie-generation-block-size: 100
    min-role-name-length: 10
    max-role-name-length: 20